name: Deploy to Minikube

on:
  push:
    branches:
      - main  # ajuste de acordo com o nome da sua branch principal

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Check if Minikube is running
        run: |
          if ! minikube status > /dev/null 2>&1; then
              echo "Minikube is not running. Starting..."
              minikube start
          fi

      - name: Set Docker environment to Minikube
        run: source <(minikube docker-env)

      - name: Build Docker image
        run: docker build -t local/devex:v1 .

      - name: Apply Kubernetes configuration
        run: kubectl apply -f deploy/k8s.yaml
        
      - name: Sleep 10
        run: sleep 10
        
      - name: Wait for pods to be ready
        run: kubectl wait --for=condition=Ready pod --all

      - name: Expose service
        run: minikube service local-devex-svc
