name: Deploy to Minikube

on:
  push:
    branches:
      - main  # ajuste de acordo com o nome da sua branch principal

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Docker environment to Minikube
        run: minikube start && eval $(minikube docker-env) && minikube image build -t local/devex:v1 . && kubectl apply -f deploy/k8s.yaml && kubectl wait --for=condition=Ready pod --all &&  minikube service local-devex-svc
